# Generated by Django 4.1.3 on 2022-12-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('news_publisher', models.TextField(blank=True, null=True)),
                ('word_one', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'context',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_0', models.BigIntegerField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('month', models.BigIntegerField(blank=True, null=True)),
                ('day', models.BigIntegerField(blank=True, null=True)),
                ('index', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'date',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_0', models.BigIntegerField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('index', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_table',
                'managed': True,
            },
        ),
    ]
